export const GET_HOME_CAMPAIGN_LOADING = "GET_HOME_CAMPAIGN_LOADING"
export const GET_HOME_CAMPAIGN_SUCCESS = "GET_HOME_CAMPAIGN_SUCCESS"
export const GET_HOME_CAMPAIGN_ERROR = "GET_HOME_CAMPAIGN_ERROR"
export const GET_HOME_CAMPAIGN_RESET = "GET_HOME_CAMPAIGN_RESET"