export const SIGN_UP_LOADING = "SIGN_UP_LOADING"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"
export const SIGN_UP_RESET = "SIGN_UP_RESET"


export const LOGIN_UP_LOADING = "LOGIN_UP_LOADING"
export const LOGIN_UP_SUCCESS = "LOGIN_UP_SUCCESS"
export const LOGIN_UP_ERROR = "LOGIN_UP_ERROR"
export const LOGIN_UP_RESET = "LOGIN_UP_RESET"

export const LOG_OUT_UP_LOADING = "LOG_OUT_UP_LOADING"
export const LOG_OUT_UP_SUCCESS = "LOG_OUT_UP_SUCCESS"
export const LOG_OUT_UP_ERROR = "LOG_OUT_UP_ERROR"
export const LOG_OUT_UP_RESET = "LOG_OUT_UP_RESET"

