export const CAMPAIGN_LOADING = "CAMPAIGN_LOADING"
export const CAMPAIGN_SUCCESS = "CAMPAIGN_SUCCESS"
export const CAMPAIGN_ERROR = "CAMPAIGN_ERROR"
export const CAMPAIGN_RESET = "CAMPAIGN_RESET"

export const ADD_CAMPAIGN_LOADING = "ADD_CAMPAIGN_LOADING"
export const ADD_CAMPAIGN_SUCCESS = "ADD_CAMPAIGN_SUCCESS"
export const ADD_CAMPAIGN_ERROR = "ADD_CAMPAIGN_ERROR"
export const ADD_CAMPAIGN_RESET = "ADD_CAMPAIGN_RESET"


