export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_RESET = "GET_USERS_RESET";


export const LOGIN_GET_USERS_SUCCESS = "LOGIN_GET_USERS_SUCCESS"

export const LOGIN_USERS_LOADING = "LOGIN_USERS_LOADING"
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS"
export const LOGIN_USERS_ERROR = "LOGIN_USERS_ERROR"




